Repository santosomar/csaf_validator, pull requests merged in 2023-02, with the labels that each got.

#1 Convert to a module and make directly installable via GitHub URL.
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  examples/cisco_example.json
  pyproject.toml
  requirements.txt
  setup.py
  src/csaf_validator/__init__.py
  src/csaf_validator/csaf_json_schema.json
Labels: enhancement

#3 Updating the licensing to MIT
  LICENSE
Labels: documentation

#7 Update README.md
  README.md
Labels: documentation

#9 Update pyproject.toml
  pyproject.toml
Labels: good first issue
